In [1]:
from google.colab import files
uploaded = files.upload()

Saving train_signs.h5 to train_signs.h5


In [0]:
import math
import numpy as np
import h5py
import matplotlib.pyplot as plt
import scipy
from PIL import Image
from scipy import ndimage
import tensorflow as tf
from tensorflow.python.framework import ops


In [0]:
dataset = h5py.File("train_signs.h5", 'r+')

In [4]:
print(dataset)

<HDF5 file "train_signs.h5" (mode r+)>


In [5]:
list(dataset.keys())

['list_classes', 'train_set_x', 'train_set_y']

In [0]:
train_data_x = dataset['train_set_x']
train_data_y = dataset['train_set_y']
train_data_classes = dataset['list_classes']

In [7]:

print(train_data_y[0])

5


In [8]:
print(train_data_x.shape)
print(train_data_y.shape)

(1080, 64, 64, 3)
(1080,)


In [9]:
x_train = np.divide(train_data_x,255)
y_train = tf.one_hot(train_data_y, 6)
sess = tf.Session()
print(sess.run(y_train[1]))

[1. 0. 0. 0. 0. 0.]


In [10]:
print(train_data_x[1])
print("   ")
print(x_train[1])

[[[238 232 223]
  [238 232 223]
  [238 232 223]
  ...
  [222 216 209]
  [221 216 207]
  [221 216 206]]

 [[237 232 223]
  [238 232 223]
  [238 232 223]
  ...
  [222 216 209]
  [222 216 208]
  [223 217 207]]

 [[236 232 222]
  [237 232 223]
  [238 232 223]
  ...
  [222 216 209]
  [222 216 208]
  [221 216 207]]

 ...

 [[218 212 204]
  [217 212 204]
  [217 211 205]
  ...
  [214 203 194]
  [214 203 195]
  [214 204 194]]

 [[217 211 203]
  [217 211 203]
  [216 210 203]
  ...
  [214 203 194]
  [215 203 194]
  [215 204 193]]

 [[216 210 202]
  [216 210 203]
  [215 209 203]
  ...
  [214 203 194]
  [215 203 194]
  [215 204 192]]]
   
[[[0.93333333 0.90980392 0.8745098 ]
  [0.93333333 0.90980392 0.8745098 ]
  [0.93333333 0.90980392 0.8745098 ]
  ...
  [0.87058824 0.84705882 0.81960784]
  [0.86666667 0.84705882 0.81176471]
  [0.86666667 0.84705882 0.80784314]]

 [[0.92941176 0.90980392 0.8745098 ]
  [0.93333333 0.90980392 0.8745098 ]
  [0.93333333 0.90980392 0.8745098 ]
  ...
  [0.87058824 0.847

In [11]:
print(x_train.shape)

(1080, 64, 64, 3)


In [12]:
print(y_train.shape)

(1080, 6)


In [0]:
def make_placeholder(h,w,c,y):
  X = tf.placeholder(tf.float32, shape=[None,h,w,c])
  Y = tf.placeholder(tf.float32,shape=[None,y])
  return X,Y

In [0]:
X,Y = make_placeholder(64,64,3,6)

In [15]:
print (str(X)+"  "+ str(Y))

Tensor("Placeholder:0", shape=(?, 64, 64, 3), dtype=float32)  Tensor("Placeholder_1:0", shape=(?, 6), dtype=float32)


In [0]:
def initialize_parameters():
  tf.set_random_seed(1)
  W1 = tf.get_variable('W1', [4,4,3,8], initializer = tf.contrib.layers.xavier_initializer(seed=0))
  W2 = tf.get_variable('W2', [2,2,8,16], initializer = tf.contrib.layers.xavier_initializer(seed=0))
  parameters= {"W1":W1,
               "W2": W2
      
  }
  return parameters

In [28]:
tf.reset_default_graph()
with tf.Session() as tf_sess:
  parameters = initialize_parameters()
  init = tf.global_variables_initializer()
  tf_sess.run(init)
  print("W1 = " + str(parameters["W1"].eval()[1,1,1,1]))
  print("W2 = " + str(parameters["W2"].eval()[1,1,1,1]))

W1 = 0.1417614
W2 = 0.17750949


In [27]:
tf.reset_default_graph()
with tf.Session() as sess_test:
    parameters = initialize_parameters()
    init = tf.global_variables_initializer()
    sess_test.run(init)
    print("W1 = " + str(parameters["W1"].eval()))
    print("W2 = " + str(parameters["W2"].eval()))

W1 = [[[[ 0.11547081 -0.15562162  0.14463945 -0.12213563 -0.161331
     0.0167321   0.00137798  0.15687598]
   [ 0.06261188  0.15809353 -0.13944083  0.1304368   0.14947264
     0.07770665 -0.0344099   0.02789916]
   [ 0.1310067   0.03547595  0.1019934   0.17467071 -0.16157703
    -0.06069881 -0.10278072 -0.06633689]]

  [[-0.1701455  -0.15981087 -0.06383926 -0.00349012 -0.14234345
    -0.05761932  0.00821769 -0.07173218]
   [ 0.14097519  0.11141728  0.18437327  0.0588678  -0.13764857
    -0.11404216  0.05882488  0.09655331]
   [ 0.09364428 -0.03100704  0.16560768  0.14417745  0.15409656
    -0.08602516 -0.12028332 -0.16772161]]

  [[ 0.18019755 -0.17030357 -0.10018802 -0.18330556  0.03716455
    -0.09169444 -0.01606575 -0.10697315]
   [-0.1352132   0.04067522  0.07451691  0.02565144 -0.08935398
    -0.14955646  0.17125843 -0.10636543]
   [ 0.1641133  -0.16645104  0.14331098 -0.0984499  -0.02071032
    -0.13608913  0.15722917 -0.05736801]]

  [[ 0.18048044  0.12755601  0.09927674 -0.078

In [0]:
def forward_propagation(X, parameters):
  W1 = parameters["W1"]
  W2 = parameters["W2"]
  z1 = tf.nn.conv2d(X,W1,strides = [1,1,1,1], padding = 'SAME')
  a1 = tf.nn.relu(z1)
  p1 = tf.nn.max_pool(a1,ksize = [1,8,8,1], strides = [1,8,8,1], padding = 'SAME'  )
  z2 = tf.nn.conv2d(p1,W2,strides = [1,1,1,1], padding = 'SAME')
  a2 = tf.nn.relu(z2)
  p2 = tf.nn.max_pool(a2,ksize = [1,4,4,1], strides = [1,4,4,1], padding = 'SAME'  )
  output = tf.contrib.layers.flatten(p2)
  z3 = tf.contrib.layers.fully_connected(z3,6,activation_fn = None)
  return z3
  

In [0]:
def compute_cost(z3,Y):
  cost = tf.nn.softmax_cross_entropy_with_logits(logits = z3, labels = Y)
  cost = tf.reduce_mean(cost)
  return cost

In [0]:
def model(x_train,y_train, learning_rate = 0.009, num_epochs = 250, minibatch_size = 100, print_cost = True):
  ops.reset_default_graph()
  tf.random_seed(1)
  seed = 3
  (m,h,w,c) = x_train.shape
  (y) = y_train.shape[1]
  X,Y = make_placeholder(h,w,c,y)
  parameters = initialize_parameters()
  z3 = forward_propagation(X, parameters)
  cost = compute_cost(z3,Y)
  optimizer = tf.train.AdamOptimizer(learning_rate = learning_rate).minimize(cost)
  init = tf.global_variables_initializer()
  with tf.Session() as sess:
    sess.run(init)
    for epoch in range(num_epochs):
      
    
    
  